import { PreferenceSection } from './types';
import {
  countries,
  interests,
  relationshipTypes,
  genderPreferences,
  communicationStyles,
  responseTimes,
  lifestyleOptions,
  exerciseOptions,
  dietOptions,
  educationOptions,
  careerOptions,
  politicalViews,
  messagePrivacyOptions,
  languages,
  ageRanges,
  importanceLevels,
  searchRadiusOptions,
  matchQualityOptions,
  languageProficiency,
} from './preference-data';

export const preferenceSections: PreferenceSection[] = [
  {
    id: 'basic',
    title: 'Basic Preferences',
    description: 'Set your fundamental matching criteria',
    icon: '⚙️',
    fields: [
      {
        id: 'ageRange',
        type: 'range',
        label: 'Age Range',
        min: 18,
        max: 80,
        step: 1,
        required: true,
        description: 'Select your preferred age range for matches',
      },
      {
        id: 'genderPreference',
        type: 'select',
        label: 'Interested in',
        options: genderPreferences,
        required: true,
        description: 'Choose which genders you want to match with',
      },
      {
        id: 'relationshipType',
        type: 'select',
        label: 'Looking for',
        options: relationshipTypes,
        required: true,
        description: 'What type of relationship are you seeking?',
      },
    ],
  },
  {
    id: 'location',
    title: 'Location Preferences',
    description: 'Set your location and distance preferences',
    icon: '📍',
    fields: [
      {
        id: 'location',
        type: 'select',
        label: 'Primary Country',
        options: countries,
        required: true,
        description: 'Your main country for matching',
      },
      {
        id: 'location',
        type: 'text',
        label: 'City (Optional)',
        placeholder: 'Enter your city',
        description: 'Your city for more precise matching',
      },
      {
        id: 'location',
        type: 'range',
        label: 'Maximum Distance',
        min: 1,
        max: 500,
        step: 5,
        required: true,
        description: 'How far are you willing to travel for a match?',
      },
      {
        id: 'location',
        type: 'multiselect',
        label: 'Preferred Countries',
        options: countries,
        required: false,
        description: 'Select additional countries you\'re open to matching with',
      },
    ],
  },
  {
    id: 'languages',
    title: 'Language Preferences',
    description: 'Configure your language preferences for better communication',
    icon: '🗣️',
    fields: [
      {
        id: 'languages',
        type: 'select',
        label: 'Primary Language',
        options: languages,
        required: true,
        description: 'Your main language for communication',
      },
      {
        id: 'languages',
        type: 'multiselect',
        label: 'Secondary Languages',
        options: languages,
        required: false,
        description: 'Other languages you can speak',
      },
      {
        id: 'languages',
        type: 'select',
        label: 'Language Proficiency',
        options: languageProficiency,
        required: false,
        description: 'Your proficiency level in your primary language',
      },
    ],
  },
  {
    id: 'search-config',
    title: 'Search Configuration',
    description: 'Fine-tune how your matches are found',
    icon: '🔍',
    fields: [
      {
        id: 'searchPreferences',
        type: 'select',
        label: 'Age Importance',
        options: importanceLevels,
        required: false,
        description: 'How important is age in your matching criteria?',
      },
      {
        id: 'searchPreferences',
        type: 'select',
        label: 'Location Importance',
        options: importanceLevels,
        required: false,
        description: 'How important is location in your matching criteria?',
      },
      {
        id: 'searchPreferences',
        type: 'select',
        label: 'Gender Importance',
        options: importanceLevels,
        required: false,
        description: 'How important is gender in your matching criteria?',
      },
      {
        id: 'searchPreferences',
        type: 'select',
        label: 'Language Importance',
        options: importanceLevels,
        required: false,
        description: 'How important is language in your matching criteria?',
      },
      {
        id: 'searchPreferences',
        type: 'toggle',
        label: 'Allow Long Distance',
        required: false,
        description: 'Are you open to long-distance relationships?',
      },
      {
        id: 'searchPreferences',
        type: 'select',
        label: 'Search Radius',
        options: searchRadiusOptions,
        required: false,
        description: 'How far should we search for matches?',
      },
      {
        id: 'searchPreferences',
        type: 'select',
        label: 'Match Quality',
        options: matchQualityOptions,
        required: false,
        description: 'Preference for match quality vs quantity',
      },
      {
        id: 'searchPreferences',
        type: 'toggle',
        label: 'Show Verified Profiles Only',
        required: false,
        description: 'Only show profiles that have been verified',
      },
      {
        id: 'searchPreferences',
        type: 'toggle',
        label: 'Show Online Users Only',
        required: false,
        description: 'Only show users who are currently online',
      },
    ],
  },
  {
    id: 'interests',
    title: 'Interests & Hobbies',
    description: 'Select interests you want to match with',
    icon: '🎯',
    fields: [
      {
        id: 'interests',
        type: 'multiselect',
        label: 'Interests',
        options: interests,
        required: false,
        description: 'Select interests that matter to you in a match',
      },
    ],
  },
  {
    id: 'communication',
    title: 'Communication Preferences',
    description: 'How you prefer to communicate',
    icon: '💬',
    fields: [
      {
        id: 'communicationStyle',
        type: 'select',
        label: 'Preferred Communication',
        options: communicationStyles,
        required: false,
        description: 'How do you prefer to communicate with matches?',
      },
      {
        id: 'responseTime',
        type: 'select',
        label: 'Expected Response Time',
        options: responseTimes,
        required: false,
        description: 'What response time do you expect from matches?',
      },
    ],
  },
  {
    id: 'lifestyle',
    title: 'Lifestyle Preferences',
    description: 'Your lifestyle and habits preferences',
    icon: '🌿',
    fields: [
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Smoking',
        options: lifestyleOptions,
        required: false,
        description: 'Your preference regarding smoking',
      },
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Drinking',
        options: lifestyleOptions,
        required: false,
        description: 'Your preference regarding drinking',
      },
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Exercise Frequency',
        options: exerciseOptions,
        required: false,
        description: 'How often do you exercise?',
      },
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Diet',
        options: dietOptions,
        required: false,
        description: 'Your dietary preferences',
      },
    ],
  },
  {
    id: 'education',
    title: 'Education & Career',
    description: 'Educational and career preferences',
    icon: '🎓',
    fields: [
      {
        id: 'education',
        type: 'select',
        label: 'Education Level',
        options: educationOptions,
        required: false,
        description: 'Your preferred education level in matches',
      },
      {
        id: 'career',
        type: 'select',
        label: 'Career Status',
        options: careerOptions,
        required: false,
        description: 'Your preferred career status in matches',
      },
    ],
  },
  {
    id: 'additional',
    title: 'Additional Preferences',
    description: 'Other important preferences',
    icon: '✨',
    fields: [
      {
        id: 'religion',
        type: 'text',
        label: 'Religion (Optional)',
        placeholder: 'Enter your religion',
        description: 'Your religious preferences',
      },
      {
        id: 'politicalViews',
        type: 'select',
        label: 'Political Views',
        options: politicalViews,
        required: false,
        description: 'Your political preference in matches',
      },
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy Settings',
    description: 'Control your privacy and messaging preferences',
    icon: '🔒',
    fields: [
      {
        id: 'privacy',
        type: 'toggle',
        label: 'Show Online Status',
        required: false,
        description: 'Let others see when you\'re online',
      },
      {
        id: 'privacy',
        type: 'toggle',
        label: 'Show Last Seen',
        required: false,
        description: 'Let others see when you were last active',
      },
      {
        id: 'privacy',
        type: 'select',
        label: 'Allow Messages From',
        options: messagePrivacyOptions,
        required: false,
        description: 'Who can send you messages?',
      },
      {
        id: 'privacy',
        type: 'toggle',
        label: 'Show Age',
        required: false,
        description: 'Display your age to other users',
      },
      {
        id: 'privacy',
        type: 'toggle',
        label: 'Show Location',
        required: false,
        description: 'Display your location to other users',
      },
      {
        id: 'privacy',
        type: 'toggle',
        label: 'Show Interests',
        required: false,
        description: 'Display your interests to other users',
      },
    ],
  },
];
