import { PreferenceSection } from './types';
import {
  countries,
  interests,
  relationshipTypes,
  genderPreferences,
  communicationStyles,
  responseTimes,
  lifestyleOptions,
  exerciseOptions,
  dietOptions,
  educationOptions,
  careerOptions,
  politicalViews,
  messagePrivacyOptions,
  languages,
} from './preference-data';

export const preferenceSections: PreferenceSection[] = [
  {
    id: 'basic',
    title: 'Basic Preferences',
    description: 'Set your fundamental matching criteria',
    icon: '⚙️',
    fields: [
      {
        id: 'ageRange',
        type: 'range',
        label: 'Age Range',
        min: 18,
        max: 80,
        step: 1,
        required: true,
      },
      {
        id: 'genderPreference',
        type: 'select',
        label: 'Interested in',
        options: genderPreferences,
        required: true,
      },
      {
        id: 'relationshipType',
        type: 'select',
        label: 'Looking for',
        options: relationshipTypes,
        required: true,
      },
    ],
  },
  {
    id: 'location',
    title: 'Location Preferences',
    description: 'Set your location and distance preferences',
    icon: '📍',
    fields: [
      {
        id: 'location',
        type: 'select',
        label: 'Country',
        options: countries,
        required: true,
      },
      {
        id: 'location',
        type: 'text',
        label: 'City (Optional)',
        placeholder: 'Enter your city',
      },
      {
        id: 'location',
        type: 'range',
        label: 'Maximum Distance',
        min: 1,
        max: 500,
        step: 5,
        required: true,
      },
    ],
  },
  {
    id: 'interests',
    title: 'Interests & Hobbies',
    description: 'Select interests you want to match with',
    icon: '🎯',
    fields: [
      {
        id: 'interests',
        type: 'multiselect',
        label: 'Interests',
        options: interests,
        required: false,
      },
    ],
  },
  {
    id: 'communication',
    title: 'Communication Preferences',
    description: 'How you prefer to communicate',
    icon: '💬',
    fields: [
      {
        id: 'communicationStyle',
        type: 'select',
        label: 'Preferred Communication',
        options: communicationStyles,
        required: false,
      },
      {
        id: 'responseTime',
        type: 'select',
        label: 'Expected Response Time',
        options: responseTimes,
        required: false,
      },
    ],
  },
  {
    id: 'lifestyle',
    title: 'Lifestyle Preferences',
    description: 'Your lifestyle and habits preferences',
    icon: '🌿',
    fields: [
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Smoking',
        options: lifestyleOptions,
        required: false,
      },
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Drinking',
        options: lifestyleOptions,
        required: false,
      },
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Exercise Frequency',
        options: exerciseOptions,
        required: false,
      },
      {
        id: 'lifestyle',
        type: 'select',
        label: 'Diet',
        options: dietOptions,
        required: false,
      },
    ],
  },
  {
    id: 'education',
    title: 'Education & Career',
    description: 'Educational and career preferences',
    icon: '🎓',
    fields: [
      {
        id: 'education',
        type: 'select',
        label: 'Education Level',
        options: educationOptions,
        required: false,
      },
      {
        id: 'career',
        type: 'select',
        label: 'Career Status',
        options: careerOptions,
        required: false,
      },
    ],
  },
  {
    id: 'additional',
    title: 'Additional Preferences',
    description: 'Other important preferences',
    icon: '✨',
    fields: [
      {
        id: 'languages',
        type: 'multiselect',
        label: 'Languages',
        options: languages,
        required: false,
      },
      {
        id: 'politicalViews',
        type: 'select',
        label: 'Political Views',
        options: politicalViews,
        required: false,
      },
      {
        id: 'religion',
        type: 'text',
        label: 'Religion (Optional)',
        placeholder: 'Enter your religion',
      },
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy Settings',
    description: 'Control your privacy and messaging preferences',
    icon: '🔒',
    fields: [
      {
        id: 'privacy',
        type: 'toggle',
        label: 'Show Online Status',
        required: false,
      },
      {
        id: 'privacy',
        type: 'toggle',
        label: 'Show Last Seen',
        required: false,
      },
      {
        id: 'privacy',
        type: 'select',
        label: 'Allow Messages From',
        options: messagePrivacyOptions,
        required: false,
      },
    ],
  },
];
